spring:
  application:
    name: lotto
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

lotto:
  init: ${LOTTO_INIT:false}
  id: ${LOTTO_ID:}
  password: ${LOTTO_PASSWORD:}
  email: ${LOTTO_EMAIL:}
  count: ${LOTTO_COUNT:5}
  cron:
    check: ${LOTTO_CRON_CHECK:0 0 22 * * 6}
    buy: ${LOTTO_CRON_BUY:0 0 9 * * 0}