import os


class Config:
  # LOTTO_ID = os.environ.get('LOTTO_ID')
  # LOTTO_PASSWORD = os.environ.get('LOTTO_PASSWORD')
  LOTTO_ID = "mks269109"
  LOTTO_PASSWORD = "mun@269109"
  LOTTO_SCHEDULE = os.environ.get('LOTTO_SCHEDULE')
  LOTTO_NOTIFICATIONS = os.environ.get('LOTTO_NOTIFICATIONS')
  LOTTO_COUNT = os.environ.get('LOTTO_COUNT')


class GithubConfig(Config):
  GITHUB_TOKEN = os.environ.get('GITHUB_TOKEN')
  GITHUB_REPOSITORY = os.environ.get('GITHUB_REPOSITORY')


class EmailConfig(Config):
  NOTIFICATION_EMAIL_SERVER = os.environ.get('NOTIFICATION_EMAIL_SERVER')
  NOTIFICATION_EMAIL_SERVER_PORT = os.environ.get('NOTIFICATION_EMAIL_SERVER_PORT')
  NOTIFICATION_EMAIL_SERVER_PASSWORD = os.environ.get('NOTIFICATION_EMAIL_SERVER_PASSWORD')
  NOTIFICATION_EMAIL_TO = os.environ.get('NOTIFICATION_EMAIL_TO')
  NOTIFICATION_EMAIL_FROM = os.environ.get('NOTIFICATION_EMAIL_FROM')
