name: Deploy to GHCR

on:
  release:
    types: [released]

jobs:
  push_to_registry:
    name: Push Docker image to GHCR
    runs-on: ubuntu-latest
    steps:
      - name: "[INIT] Check out the repo"
        uses: actions/checkout@v4

      - name: "[SET] Set up QEMU"
        uses: docker/setup-qemu-action@v3

      - name: "[SET] Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3

      - name: "[SET] Login to GHCR"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: "[RUN] Build and push"
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max