name: Lotto purchase (cron)
on:
  schedule:
    # 매 주 일요일 오후 12시, Github Actions 에서는 UTC 기준으로 실행됨
    # https://elmah.io/tools/cron-parser/
    - cron: '0 0 * * 3'
  workflow_dispatch:

jobs:
  run-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rich-automation/lotto-action@latest
        with:
          id: ${{ secrets.LOTTO_ID }}
          pwd: ${{ secrets.LOTTO_PASSWORD }}
          token: ${{ secrets.GITHUB_TOKEN }}