name: Lotto

on:
  schedule:
    - cron: '0 3 * * 0' # UTC 기준, 매주 일요일 12:00 KST
  workflow_dispatch:

jobs:
  setup-python:
    runs-on: ubuntu-latest
    name: Setup Python

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps

  buy-lotto:
    runs-on: ubuntu-latest
    name: Buy Lotto and Send Result
    needs: setup-python

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Restore cached packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps

      - name: Buy Lotto
        run: python lotto_buy.py
        env:
          LOTTO_ID: ${{ secrets.LOTTO_ID }}
          LOTTO_PASSWORD: ${{ secrets.LOTTO_PASSWORD }}
          GITHUB_TOKEN: ${{ github.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.GITHUB_GITHUB_REPOSITORY }}

  update-issue:
    runs-on: ubuntu-latest
    name: Update Issue
    needs: setup-python

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Restore cached packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps

      - name: Update Issue
        run: python lotto_result.py
        env:
          LOTTO_ID: ${{ secrets.LOTTO_ID }}
          LOTTO_PASSWORD: ${{ secrets.LOTTO_PASSWORD }}
          GITHUB_TOKEN: ${{ github.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.GITHUB_GITHUB_REPOSITORY }}
