name: Lotto

on:
  schedule:
    # 매 주 일요일 오후 12시, Github Actions 에서는 UTC 기준으로 실행됨
    # https://elmah.io/tools/cron-parser/
    - cron: '0 0 * * 3'
  workflow_dispatch:
  
jobs:
  lotto:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ "3.10" ]

    steps:
      - name: "[INIT] Clone repository"
        uses: actions/checkout@v4

      - name: "[SET] Setup python ${{ matrix.python-version }}"
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: "[SET] Install python package"
        run: |
          pip install -r requirements.txt
          python -m playwright install --with-deps

      - name: "[RUN] Buy Lotto and Send Result"
        run: |
          python lotto_buy.py
        env:
          LOTTO_ID: ${{ secrets.LOTTO_ID }}
          LOTTO_PASSWORD: ${{ secrets.LOTTO_PASSWORD }}
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_REPOSITORY: ${{ github.repository }}

  result:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ "3.10" ]

    steps:
      - name: "[INIT] Clone repository"
        uses: actions/checkout@v4

      - name: "[SET] Setup python ${{ matrix.python-version }}"
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: "[SET] Install python package"
        run: |
          pip install -r requirements.txt
          python -m playwright install --with-deps

      - name: "[RUN] Issue Update"
        run: |
          python lotto_result.py
        env:
          LOTTO_ID: ${{ secrets.LOTTO_ID }}
          LOTTO_PASSWORD: ${{ secrets.LOTTO_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
