name: Lotto

on:
  workflow_dispatch:
  
jobs:
  lotto:
    runs-on: ubuntu-latest
    steps:
      - name: "[INIT] Clone repository"
        uses: actions/checkout@v4

      - name: "[SET] Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: "[SET] Install python package"
        run: |
          pip install -r requirements.txt
          python -m playwright install --with-deps

      - name: "[RUN] Buy Lotto and Send Result"
        run: |
          python src/LottoServiceApplication.py
        env:
          LOTTO_ID: ${{ secrets.LOTTO_ID }}
          LOTTO_PASSWORD: ${{ secrets.LOTTO_PASSWORD }}
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_REPOSITORY: ${{ github.repository }}
