name: Update README

on:
  push:
    paths:
      - 'docker-compose.yaml'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: "[INIT] Check out code"
        uses: actions/checkout@v4

      - name: "[SET] Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: "[RUN] Update README"
        run: |
          python -c "\
          # Read docker-compose.yaml\n\
          with open('docker-compose.yaml', 'r') as file:\n\
            data = file.read()\n\
          \n\
          # Format as Markdown\n\
            markdown = '```yaml\\n' + data + '\\n```'\n\
          \n\
          # Read README.md\n\
          with open('README.md', 'r') as file:\n\
            readme = file.read()\n\
          \n\
          # Replace the Docker section\n\
            start = readme.index('```yaml')\n\
            end = readme.index('```', start + 1) + 3\n\
            updated_readme = readme[:start] + markdown + readme[end:]\n\
          \n\
          # Write back to README.md\n\
          with open('README.md', 'w') as file:\n\
            file.write(updated_readme)\n\
          "

      - name: "[RUN] Commit and push if it changed"
        run: |
          git diff
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git commit -am "Update README.md" && git push origin || echo "No changes to commit"